version: 2

jobs:
  test:
    docker:
      - image: circleci/openjdk:stretch

    steps:
      - checkout
      - run: ./mvnw test
     - run: ./mvnw -Dmaven.test.skip=true package

workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build-and-test